schema = 3

[mod]
  [mod."github.com/btcsuite/btcd"]
    version = "v0.23.0"
    hash = "sha256-cDMCqIriUzp/thVg46V0+CDKRQAGZvaIjmdYbYKM1aM="
  [mod."github.com/btcsuite/btcd/btcec/v2"]
    version = "v2.1.3"
    hash = "sha256-qAahjPElRpX4L3NpyOOVZi5NOhqAQ+trGW26bXm+emo="
  [mod."github.com/btcsuite/btcd/btcutil"]
    version = "v1.1.3"
    hash = "sha256-6Y9sP1yvPBO8PhqmFVVXNV7dxsXlERDAB+TPTEfW3kI="
  [mod."github.com/btcsuite/btcd/chaincfg/chainhash"]
    version = "v1.0.1"
    hash = "sha256-vix0j/KGNvoKjhlKgVeSLY6un2FHeIEoZWMC4z3yvZ4="
  [mod."github.com/decred/dcrd/dcrec/secp256k1/v4"]
    version = "v4.0.1"
    hash = "sha256-JBVRp40dDj0puapoQloV13H6TMjgJiypzYojcDRE2jI="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.4.0"
    hash = "sha256-LwOrfDN5fx/R2lgaD90RIu2NxcJDpyqYEURLc9Kgxgw="
  [mod."github.com/skip2/go-qrcode"]
    version = "v0.0.0-20200617195104-da1b6568686e"
    hash = "sha256-ST9t4/b7WFXUb8wra4ZYVDNZJGrEykw8dkWhLrxp8F0="
  [mod."github.com/srwiley/rasterx"]
    version = "v0.0.0-20220730225603-2ab79fcdd4ef"
    hash = "sha256-/XmSE/J+f6FLWXGvljh6uBK71uoCAK3h82XQEQ1Ki68="
  [mod."github.com/tarm/serial"]
    version = "v0.0.0-20180830185346-98f6abe2eb07"
    hash = "sha256-646ngos1o2K+T+wxZpfuaQKrWqWZuta5iqMPJ3aURPo="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."golang.org/x/crypto"]
    version = "v0.4.0"
    hash = "sha256-PvHIbuooDItiNyQEi8kKgybkc0o95B0aeMd9awVGFCY="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20220722155232-062f8c9fd539"
    hash = "sha256-Rl3kKCUy5h1CqLsA87vyg3fSb05qKjd3tI6QvC1LfkI="
  [mod."golang.org/x/sys"]
    version = "v0.3.0"
    hash = "sha256-TIHhfYbZ99sCU1ZMikxwomXH5AEtD/lA1VMMW+UAhbU="
  [mod."golang.org/x/text"]
    version = "v0.5.0"
    hash = "sha256-ztH+xQyM/clOcQl+y/UEPcfNKbc3xApMbEPDDZ9up0o="
  [mod."periph.io/x/conn/v3"]
    version = "v3.7.0"
    hash = "sha256-UL6B0d9K8T3XrSYDrHDeaKAdkUh/Wf+NdhPRriE8Bzw="
  [mod."periph.io/x/host/v3"]
    version = "v3.8.0"
    hash = "sha256-ZxiY79iCHA9Cs8+teb4TX3N6pzEzgRvdlcvww1qQ9dE="
